### ISSUE TITLE
Integrate graphics & networking

### ISSUE THREAD

**Issue by hgrehm** [ucsd-cse125-sp24/group4#18]
Ensure input received in one process can be sent to the graphics client, running in another process, to affect some aspect of the virtual world or how the user views it

**Comment by zfxd** [comment]
This is very general lol and partly done - I think we can split this up into further tasks

**Comment by hgrehm** [comment]
Yeah I agree. I think getting the packet structures done and debugging the server are probably prerequisites to finishing this more completely. What would you have in mind to splitting this one into further tasks?
